### ISSUE TITLE
JlinkTest_RequiredMod fails on macos  

### ISSUE THREAD

**Issue by Mesbah-Alam** [AdoptOpenJDK/openjdk-systemtest#147]
JlinkTest_RequiredMod_0 fails on macos as it can't find JniTest binary in lib path: 

```
T2  stderr Exception in thread "main" java.lang.UnsatisfiedLinkError: no JniTest in java.library.path: [/Users/jenkins/workspace/openjdk10_hs_systemtest_x86-64_macos/openjdk-tests/TestConfig/scripts/testKitGen/../../../TestConfig/test_output_15317610566014/JlinkTest_RequiredMod_0/20180716-114035-JlinkTest/tmp/../native/]
T2  stderr 	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2654)
T2  stderr 	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:876)
T2  stderr 	at java.base/java.lang.System.loadLibrary(System.java:1875)
T2  stderr 	at com.test.jlink/adoptopenjdk.test.modularity.jlink.JniTest.<clinit>(JniTest.java:24)
T2  stderr 	at java.base/java.lang.Class.forName0(Native Method)
T2  stderr 	at java.base/java.lang.Class.forName(Class.java:374)
T2  stderr 	at org.junit.internal.Classes.getClass(Classes.java:16)
T2  stderr 	at org.junit.runner.JUnitCommandLineParseResult.parseParameters(JUnitCommandLineParseResult.java:100)
T2  stderr 	at org.junit.runner.JUnitCommandLineParseResult.parseArgs(JUnitCommandLineParseResult.java:50)
T2  stderr 	at org.junit.runner.JUnitCommandLineParseResult.parse(JUnitCommandLineParseResult.java:44)
T2  stderr 	at org.junit.runner.JUnitCore.runMain(JUnitCore.java:72)
T2  stderr 	at org.junit.runner.JUnitCore.main(JUnitCore.java:36)
```

**Build link**
https://ci.adoptopenjdk.net/view/System%20tests/job/openjdk10_hs_systemtest_x86-64_macos/88/tapResults/

**Comment by Mesbah-Alam** [comment]
Closing as dup of https://github.com/AdoptOpenJDK/openjdk-systemtest/issues/203
