### ISSUE TITLE
ClassLoadingTest fails on JDK 11 

### ISSUE THREAD

**Issue by Mesbah-Alam** [AdoptOpenJDK/openjdk-systemtest#169]
Error: 
```
CLT java.lang.ClassNotFoundException: Failed to load Class: javax.transaction.InvalidTransactionExceptionjava.lang.ClassNotFoundException: javax.transaction.InvalidTransactionException
CLT 	at net.adoptopenjdk.test.classloading.ClassMapHog.run(ClassMapHog.java:106)
CLT 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(java.base@11-internal/Native Method)
CLT 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(java.base@11-internal/NativeMethodAccessorImpl.java:62)
CLT 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(java.base@11-internal/DelegatingMethodAccessorImpl.java:43)
CLT 	at java.lang.reflect.Method.invoke(java.base@11-internal/Method.java:566)
CLT 	at net.adoptopenjdk.loadTest.adaptors.ArbitraryJavaAdaptor.executeTest(ArbitraryJavaAdaptor.java:101)
CLT 	at net.adoptopenjdk.loadTest.LoadTestRunner$2.run(LoadTestRunner.java:177)
CLT 	at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@11-internal/ThreadPoolExecutor.java:1128)
CLT 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@11-internal/ThreadPoolExecutor.java:628)
CLT 	at java.lang.Thread.run(java.base@11-internal/Thread.java:825)
CLT <<<
```

https://ci.eclipse.org/openj9/view/Test/job/Test-sanity.system-JDK11-linux_x86-64/16/tapResults/

**Comment by Mesbah-Alam** [comment]
This test loads classes from the list: /openjdk.test.classloading/src/test.classloading/net/adoptopenjdk/test/classloading/class.dict

In this list, we have 

```
javax.transaction.InvalidTransactionException
javax.transaction.TransactionRequiredException
javax.transaction.TransactionRolledbackException
```

These classes have been removed from JDK11. So, the test can't attempt to load them while on JDK 11.

**Comment by Mesbah-Alam** [comment]
The CORBA classes also can't be loaded with JDK 11. So, the fix should be to add a check in the test to not load unavailable classes.
