### ISSUE TITLE
Modularity Layers Stress test fails in jdk11 

### ISSUE THREAD

**Issue by Mesbah-Alam** [AdoptOpenJDK/openjdk-systemtest#197]
Exception : 

```
1) testStressLayers(net.adoptopenjdk.test.modularity.junit.TestStressLayers)
T1  java.util.concurrent.ExecutionException: java.lang.NullPointerException
T1  	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
T1  	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
T1  	at com.test/net.adoptopenjdk.test.modularity.junit.TestStressLayers.stressLayersWith(TestStressLayers.java:114)
T1  	at com.test/net.adoptopenjdk.test.modularity.junit.TestStressLayers.testStressLayers(TestStressLayers.java:92)
T1  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
T1  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
T1  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
T1  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
T1  	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
T1  	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
T1  	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
T1  	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
T1  	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
T1  	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
T1  	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
T1  	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
T1  	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
T1  	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
T1  	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
T1  	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
T1  	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
T1  	at org.junit.runners.Suite.runChild(Suite.java:128)
T1  	at org.junit.runners.Suite.runChild(Suite.java:27)
T1  	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
T1  	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
T1  	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
T1  	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
T1  	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
T1  	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
T1  	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
T1  	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
T1  	at org.junit.runner.JUnitCore.runMain(JUnitCore.java:77)
T1  	at org.junit.runner.JUnitCore.main(JUnitCore.java:36)
T1  Caused by: java.lang.NullPointerException
T1  	at com.test/net.adoptopenjdk.test.modularity.junit.TestStressLayers$LayerWorkerThread_With_PlatformModules.call(TestStressLayers.java:179)
T1  	at com.test/net.adoptopenjdk.test.modularity.junit.TestStressLayers$LayerWorkerThread_With_PlatformModules.call(TestStressLayers.java:163)
T1  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
T1  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
T1  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
T1  	at java.base/java.lang.Thread.run(Thread.java:834)
T1  
```

https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/465/tapResults/

**Comment by lumpfish** [comment]
Affected test targets are `CLStressLayers` and `CLStressCRI`.
Issue still occurs, investigating.
