### ISSUE TITLE
Malformed \uxxxx encoding error during make configure

### ISSUE THREAD

**Issue by sabkrish** [AdoptOpenJDK/openjdk-systemtest#23]
On my laptop, running make configure resulted in the below error.

c:\git\openjdk-systemtest\openjdk.build\include\top.xml:64: The following error occurred while executing this line:
c:\git\openjdk-systemtest\openjdk.build\include\top.xml:447: java.lang.IllegalArgumentException: Malformed \uxxxx encoding.
at java.util.Properties.loadConvert(Properties.java:618)
at java.util.Properties.load0(Properties.java:435)
at java.util.Properties.load(Properties.java:364)
at org.apache.tools.ant.taskdefs.LoadProperties.execute(LoadProperties.java:199)
.
.

In top.xml, in the "set-platform-properties" macrodefinition, output of the command "java -XshowSettings:properties -version" is redirected into a property file. In the next step, using ant's loadproperties, the property file is read.

The issue is because of "\u" character appearing in the PATH. I had an entry in PATH env variable which is like "C:\stf\unzip". Since "\u" is coming up in the path "C:\stf**\u**nzip", ant loadproperties fails with the mentioned error.

Path entries in the generated property file appears with single "" slash. Solution to fix this problem is to change it to "\" slash.

**Comment by sabkrish** [comment]
test
