### ISSUE TITLE
LambdaLoadTest_Hotspot_0 fails with OOM on JDK8 Hotspot s390 VM

### ISSUE THREAD

**Issue by Mesbah-Alam** [AdoptOpenJDK/openjdk-systemtest#233]
LambdaLoadTest_Hotspot_0 fails with OOM on JDk8 Hotspot s390 VM

**Error:** 

```
java.lang.OutOfMemoryError: Java heap space
LT  	at java.util.concurrent.ForkJoinTask.recordExceptionalCompletion(ForkJoinTask.java:471) ~[?:1.8.0_202-internal]
LT  	at java.util.concurrent.CountedCompleter.internalPropagateException(CountedCompleter.java:723) ~[?:1.8.0_202-internal]
LT  	at java.util.concurrent.ForkJoinTask.setExceptionalCompletion(ForkJoinTask.java:493) ~[?:1.8.0_202-internal]
LT  	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:291) ~[?:1.8.0_202-internal]
LT  	at java.util.concurrent.ForkJoinPool$WorkQueue.execLocalTasks(ForkJoinPool.java:1040) ~[?:1.8.0_202-internal]
LT  	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1058) ~[?:1.8.0_202-internal]
LT  	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) ~[?:1.8.0_202-internal]
LT  	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_202-internal]
LT  stderr 
LT  stderr Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "ForkJoinPool-1-worker-2"
LT  stderr 
LT  stderr Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "main"
LT  17:02:53.241 - First failure detected by thread: load-1. Not creating dumps as no dump generation is requested for this load test
STF 17:03:21.388 - Heartbeat: Process LT  is still running
LT  17:06:13.885 - suite.getInventory().getInventoryFileRef(): openjdk.test.load/config/inventories/lambdasAndStreams/lambda.xml
LT  17:06:13.886 - suite.isCreateDump() : false
LT  17:06:13.886 - Test failed
LT    Failure num.  = 1
LT    Test number   = 12
LT    Test details  = 'JUnit[net.adoptopenjdk.test.streams.TestParallelStreamOperations]'
LT    Suite number  = 0
LT    Thread number = 1
LT  >>> Captured test output >>>
LT  testStarted : testRanMediumWords(net.adoptopenjdk.test.streams.TestParallelStreamOperations)
LT  testFinished: testRanMediumWords(net.adoptopenjdk.test.streams.TestParallelStreamOperations)
LT  testStarted : testAnyWord(net.adoptopenjdk.test.streams.TestParallelStreamOperations)
LT  testFinished: testAnyWord(net.adoptopenjdk.test.streams.TestParallelStreamOperations)
LT  testStarted : testRanContainLetter(net.adoptopenjdk.test.streams.TestParallelStreamOperations)
LT  testFinished: testRanContainLetter(net.adoptopenjdk.test.streams.TestParallelStreamOperations)
LT  testStarted : testCommonWord(net.adoptopenjdk.test.streams.TestParallelStreamOperations)
LT  testFailure: testCommonWord(net.adoptopenjdk.test.streams.TestParallelStreamOperations): java.lang.OutOfMemoryError
LT  java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError
LT  	at java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1006)
LT  	at net.adoptopenjdk.test.streams.TestParallelStreamOperations.lambda$testCommonWord$27(TestParallelStreamOperations.java:300)
LT  	at net.adoptopenjdk.test.streams.TestParallelStreamOperations.runTest(TestParallelStreamOperations.java:343)
LT  	at net.adoptopenjdk.test.streams.TestParallelStreamOperations.testCommonWord(TestParallelStreamOperations.java:244)
LT  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
LT  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
LT  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
LT  	at java.lang.reflect.Method.invoke(Method.java:498)
LT  	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
LT  	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
LT  	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
LT  	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
LT  	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
LT  	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
LT  	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
LT  	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
LT  	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
LT  	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
LT  	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
LT  	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
LT  	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
LT  	at org.junit.runners.Suite.runChild(Suite.java:128)
LT  	at org.junit.runners.Suite.runChild(Suite.java:27)
LT  	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
LT  	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
LT  	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
LT  	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
LT  	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
LT  	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
LT  	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
LT  	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
LT  	at net.adoptopenjdk.loadTest.adaptors.JUnitAdaptor.executeTest(JUnitAdaptor.java:130)
LT  	at net.adoptopenjdk.loadTest.LoadTestRunner$2.run(LoadTestRunner.java:182)
LT  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
LT  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
LT  	at java.lang.Thread.run(Thread.java:748)
LT  Caused by: java.lang.OutOfMemoryError
LT  	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
LT  	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
LT  	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
LT  	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
LT  	at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:598)
LT  	at java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1005)
LT  	... 35 more
LT  Caused by: java.lang.OutOfMemoryError
LT  	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
LT  	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
LT  	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
LT  	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
LT  	at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:598)
LT  	at java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:677)
LT  	at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:735)
LT  	at java.util.stream.ReduceOps$ReduceOp.evaluateParallel(ReduceOps.java:714)
LT  	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
LT  	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
LT  	at net.adoptopenjdk.test.streams.TestParallelStreamOperations.lambda$null$24(TestParallelStreamOperations.java:298)
LT  	at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1424)
LT  	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
LT  	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
LT  	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
LT  	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
LT  Caused by: java.lang.OutOfMemoryError: Java heap space
LT  testFinished: testCommonWord(net.adoptopenjdk.test.streams.TestParallelStreamOperations)
LT  testStarted : testShortLines(net.adoptopenjdk.test.streams.TestParallelStreamOperations)
LT  testFinished: testShortLines(net.adoptopenjdk.test.streams.TestParallelStreamOperations)
LT  testStarted : testLetterNos(net.adoptopenjdk.test.streams.TestParallelStreamOperations)
LT  testFinished: testLetterNos(net.adoptopenjdk.test.streams.TestParallelStreamOperations)
LT  
```

**Build link:** 
https://ci.adoptopenjdk.net/view/Test_system/job/openjdk8_hs_systemtest_s390x_linux/238/tapResults/

**Comment by Mesbah-Alam** [comment]
Grinder started: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1324/console

**Comment by Mesbah-Alam** [comment]
5x Grinder passed 100%: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1324/tapResults/

However, the OOM issue continues to happen in the build: https://ci.adoptopenjdk.net/view/Test_system/job/openjdk8_hs_systemtest_s390x_linux/240/console

**Comment by Mesbah-Alam** [comment]
Works fine, consistently, on JDK11 s390 hotspot: https://ci.adoptopenjdk.net/view/Test_system/job/openjdk11_hs_systemtest_s390x_linux/172/tapResults/

**Comment by Mesbah-Alam** [comment]
Note: JDK8 nightly build, in which the test fails, JDK11 nightly build, on which the test never fails, and the JDK8 Grinder that passes 100% -- they all run on the same machine - `test-marist-ubuntu1604-s390x-1` -- so, this does not look like a machine issue.

**Comment by Mesbah-Alam** [comment]
Note, in a [previous build,](https://ci.adoptopenjdk.net/view/Test_system/job/openjdk8_hs_systemtest_s390x_linux/237/tapResults/) LambdaLoadTest failed with a StackOverflowError error (not OOM): 

```
LT  >>> Captured test output >>>
LT  testStarted : testDeepRecursiveLambda(net.adoptopenjdk.test.lambda.TestLambdaRecursive)
LT  testFailure: testDeepRecursiveLambda(net.adoptopenjdk.test.lambda.TestLambdaRecursive): null
LT  java.lang.StackOverflowError
LT  	at java.lang.Number.<init>(Number.java:55)
LT  	at java.math.BigDecimal.<init>(BigDecimal.java:356)
LT  	at java.math.BigDecimal.valueOf(BigDecimal.java:1224)
LT  	at java.math.BigDecimal.valueOf(BigDecimal.java:1201)
LT  	at java.math.BigDecimal.add(BigDecimal.java:4432)
LT  	at java.math.BigDecimal.add(BigDecimal.java:4439)
LT  	at java.math.BigDecimal.subtract(BigDecimal.java:1439)
```

**Comment by lumpfish** [comment]
This is fixed by the changes made for https://github.com/AdoptOpenJDK/openjdk-systemtest/issues/379.  closing.
