### ISSUE TITLE
MathLoadTest_bigdecimal_0 incompatible with Java 13

### ISSUE THREAD

**Issue by pshipton** [AdoptOpenJDK/openjdk-systemtest#259]
I ran the system tests on an OpenJ9 Java 13 build, and found the following failure. It's likely related to changes in Java 13, and not specific to OpenJ9.

https://ci.eclipse.org/openj9/job/Test_openjdknext_j9_sanity.system_x86-64_windows_OpenJDK/1
```
MLT testFailure: testItem_0740(net.adoptopenjdk.test.bigdecimal.TestSuite060): expected:<-3[5953862697246314162905484746340871359614113505168999319783495360631452156005707752117911726553375634308091790702876492846864265377892836553693509340707503397209982115310256415249098018077865788815173701691026788460916647380644589633161711866424669654959565240828944633747635436183859976250080805236824971673600000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000]> but was:<-3[.59538626972463141629054847463408713596141135051689993197834953606314521560057077521179117265533756343080917907028764928468642653778928365536935093407075033972099821153102564152490980180778657888151737016910267884609166473806445896331617118664246696549595652408289446337476354361838599762500808052368249716736E+616]>
MLT org.junit.ComparisonFailure: expected:<-3[5953862697246314162905484746340871359614113505168999319783495360631452156005707752117911726553375634308091790702876492846864265377892836553693509340707503397209982115310256415249098018077865788815173701691026788460916647380644589633161711866424669654959565240828944633747635436183859976250080805236824971673600000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000]> but was:<-3[.59538626972463141629054847463408713596141135051689993197834953606314521560057077521179117265533756343080917907028764928468642653778928365536935093407075033972099821153102564152490980180778657888151737016910267884609166473806445896331617118664246696549595652408289446337476354361838599762500808052368249716736E+616]>
MLT 	at org.junit.Assert.assertEquals(Assert.java:115)
MLT 	at org.junit.Assert.assertEquals(Assert.java:144)
MLT 	at net.adoptopenjdk.test.bigdecimal.TestSuite060.testItem_0740(TestSuite060.java:5209)
```

https://ci.eclipse.org/openj9/job/Test_openjdknext_j9_sanity.system_ppc64le_linux_OpenJDK/1
```
MLT testFailure: testItem_0743(net.adoptopenjdk.test.bigdecimal.TestSuite055): expected:<3[20]> but was:<3[.2E+2]>
MLT org.junit.ComparisonFailure: expected:<3[20]> but was:<3[.2E+2]>
MLT 	at org.junit.Assert.assertEquals(Assert.java:115)
MLT 	at org.junit.Assert.assertEquals(Assert.java:144)
MLT 	at net.adoptopenjdk.test.bigdecimal.TestSuite055.testItem_0743(TestSuite055.java:5250)
```

https://ci.eclipse.org/openj9/job/Test_openjdknext_j9_sanity.system_x86-64_linux_xl_OpenJDK/1
```
MLT testFailure: testItem_0113(net.adoptopenjdk.test.bigdecimal.TestSuite048): expected:<3[20]> but was:<3[.2E+2]>
MLT org.junit.ComparisonFailure: expected:<3[20]> but was:<3[.2E+2]>
MLT 	at org.junit.Assert.assertEquals(Assert.java:115)
MLT 	at org.junit.Assert.assertEquals(Assert.java:144)
MLT 	at net.adoptopenjdk.test.bigdecimal.TestSuite048.testItem_0113(TestSuite048.java:762)

MLT testFailure: testItem_0205(net.adoptopenjdk.test.bigdecimal.TestSuite048): expected:<-3[00]> but was:<-3[E+2]>
MLT org.junit.ComparisonFailure: expected:<-3[00]> but was:<-3[E+2]>
MLT 	at org.junit.Assert.assertEquals(Assert.java:115)
MLT 	at org.junit.Assert.assertEquals(Assert.java:144)
MLT 	at net.adoptopenjdk.test.bigdecimal.TestSuite048.testItem_0205(TestSuite048.java:1424)

MLT testFailure: testItem_0328(net.adoptopenjdk.test.bigdecimal.TestSuite033): expected:<6[00]> but was:<6[E+2]>
MLT org.junit.ComparisonFailure: expected:<6[00]> but was:<6[E+2]>
MLT 	at org.junit.Assert.assertEquals(Assert.java:115)
MLT 	at org.junit.Assert.assertEquals(Assert.java:144)
MLT 	at net.adoptopenjdk.test.bigdecimal.TestSuite033.testItem_0328(TestSuite033.java:2372)
```

https://ci.eclipse.org/openj9/job/Test_openjdknext_j9_sanity.system_s390x_linux_OpenJDK/1
```
MLT testFailure: testItem_0402(net.adoptopenjdk.test.bigdecimal.TestSuite005): expected:<1[0]> but was:<1[E+1]>
MLT org.junit.ComparisonFailure: expected:<1[0]> but was:<1[E+1]>
MLT 	at org.junit.Assert.assertEquals(Assert.java:115)
MLT 	at org.junit.Assert.assertEquals(Assert.java:144)
MLT 	at net.adoptopenjdk.test.bigdecimal.TestSuite005.testItem_0402(TestSuite005.java:2820)

MLT testFailure: testItem_0409(net.adoptopenjdk.test.bigdecimal.TestSuite041): expected:<1[0]> but was:<1[E+1]>
MLT org.junit.ComparisonFailure: expected:<1[0]> but was:<1[E+1]>
MLT 	at org.junit.Assert.assertEquals(Assert.java:115)
MLT 	at org.junit.Assert.assertEquals(Assert.java:144)
MLT 	at net.adoptopenjdk.test.bigdecimal.TestSuite041.testItem_0409(TestSuite041.java:2726)
```

https://ci.eclipse.org/openj9/job/Test_openjdknext_j9_sanity.system_x86-64_linux_OpenJDK/1
```
MLT testFailure: testItem_0064(net.adoptopenjdk.test.bigdecimal.TestSuite054): expected:<0[]> but was:<0[E+1]>
MLT org.junit.ComparisonFailure: expected:<0[]> but was:<0[E+1]>
MLT 	at org.junit.Assert.assertEquals(Assert.java:115)
MLT 	at org.junit.Assert.assertEquals(Assert.java:144)
MLT 	at net.adoptopenjdk.test.bigdecimal.TestSuite054.testItem_0064(TestSuite054.java:441)

MLT testFailure: testItem_0464(net.adoptopenjdk.test.bigdecimal.TestSuite054): expected:<0[]> but was:<0[E+2147483647]>
MLT org.junit.ComparisonFailure: expected:<0[]> but was:<0[E+2147483647]>
MLT 	at org.junit.Assert.assertEquals(Assert.java:115)
MLT 	at org.junit.Assert.assertEquals(Assert.java:144)
MLT 	at net.adoptopenjdk.test.bigdecimal.TestSuite054.testItem_0464(TestSuite054.java:3300)

MLT testFailure: testItem_0817(net.adoptopenjdk.test.bigdecimal.TestSuite051): expected:<0[]> but was:<0[E+324]>
MLT org.junit.ComparisonFailure: expected:<0[]> but was:<0[E+324]>
MLT 	at org.junit.Assert.assertEquals(Assert.java:115)
MLT 	at org.junit.Assert.assertEquals(Assert.java:144)
MLT 	at net.adoptopenjdk.test.bigdecimal.TestSuite051.testItem_0817(TestSuite051.java:5780)
```

https://ci.eclipse.org/openj9/job/Test_openjdknext_j9_sanity.system_x86-64_mac_OpenJDK/1
```
MLT testFailure: testItem_0484(net.adoptopenjdk.test.bigdecimal.TestSuite007): expected:<0[]> but was:<0[E+1]>
MLT org.junit.ComparisonFailure: expected:<0[]> but was:<0[E+1]>
MLT 	at org.junit.Assert.assertEquals(Assert.java:115)
MLT 	at org.junit.Assert.assertEquals(Assert.java:144)
MLT 	at net.adoptopenjdk.test.bigdecimal.TestSuite007.testItem_0484(TestSuite007.java:3373)
```

**Comment by pshipton** [comment]
I could be wrong about this not being an OpenJ9 problem.
https://ci.eclipse.org/openj9/job/Test_openjdknext_j9_extended.system_ppc64le_linux_OpenJDK/1/
```
MLT testFailure: testItem_0432(net.adoptopenjdk.test.bigdecimal.TestSuite009): expected:<0[]> but was:<0[E+1]>
MLT org.junit.ComparisonFailure: expected:<0[]> but was:<0[E+1]>
MLT 	at org.junit.Assert.assertEquals(Assert.java:115)
MLT 	at org.junit.Assert.assertEquals(Assert.java:144)
MLT 	at net.adoptopenjdk.test.bigdecimal.TestSuite009.testItem_0432(TestSuite009.java:2957)
```

**Comment by pshipton** [comment]
I built a Hotspot Java 13 and confirmed that similar failures occur.
```
19:16:05  openjdk version "13-internal" 2019-09-17
19:16:05  OpenJDK Runtime Environment (build 13-internal+0-adhoc.pete.jdk)
19:16:05  OpenJDK 64-Bit Server VM (build 13-internal+0-adhoc.pete.jdk, mixed mode, sharing)
```
```
MLT testFailure: testItem_0671(net.adoptopenjdk.test.bigdecimal.TestSuite052): expected:<0[]> but was:<0[E+1]>
MLT org.junit.ComparisonFailure: expected:<0[]> but was:<0[E+1]>
MLT 	at org.junit.Assert.assertEquals(Assert.java:115)
MLT 	at org.junit.Assert.assertEquals(Assert.java:144)
MLT 	at net.adoptopenjdk.test.bigdecimal.TestSuite052.testItem_0671(TestSuite052.java:4692)
```

**Comment by Mesbah-Alam** [comment]
> I built a Hotspot Java 13 and confirmed that similar failures occur.

Does this mean we need to update the validation criteria in these tests?

**Comment by pshipton** [comment]
I'm not sure what is wrong. The failures are intermittent and not always in the same test case. Possibly it is just a bug in the OpenJDK code.

**Comment by DanHeidinga** [comment]
@Mesbah-Alam Are you looking at this?  It would be good to get this resolved as it appears to affect both OpenJ9 & Hotspot based builds.

**Comment by pshipton** [comment]
Mesbah asked 
> any further suggestion as to what we should do about this?

It seems like a test problem, where something is being changed in one thread and affecting the results in another. 
I base this conclusion on the problem occurring in both Hotspot and OpenJ9, and hitting random test cases instead of the same ones.
I suppose the test cases could be run single threaded, to determine if a failures ever occurs this way.

If you look at one of the failures `expected:<3[20]> but was:<3[.2E+2]>` the numbers are the same, just represented differently. 
Look at what the test is doing, and how it could get these different results. Then look for places in the test that change that area.

**Comment by Mesbah-Alam** [comment]
Started a Grinder where the test is being run in a single-threaded workload.

**Comment by Mesbah-Alam** [comment]
Running the tests in a single-threded workload still yields similar failures in Java 13 OpenJ9 : 

```
16:13:52  MLT testFailure: testItem_0839(net.adoptopenjdk.test.bigdecimal.TestSuite057): expected:<-9[000000000000000000]> but was:<-9[E+18]>
```

```
16:13:28  MLT testFailure: testItem_0691(net.adoptopenjdk.test.bigdecimal.TestSuite030): expected:<-1[0000000000000000000]> but was:<-1[E+19]>
```

```
16:13:28  MLT testFailure: testItem_0426(net.adoptopenjdk.test.bigdecimal.TestSuite030): expected:<4[00]> but was:<4[E+2]>
```

```
16:14:42  MLT testFailure: testItem_0761(net.adoptopenjdk.test.bigdecimal.TestSuite008): expected:<0[]> but was:<0[E+1]>
```

```
16:13:06  MLT testFailure: testItem_0174(net.adoptopenjdk.test.bigdecimal.TestSuite058): expected:<3[20]> but was:<3[.2E+2]>
```

Looking at the test code of the last test above, TestSuite058.java#testItem_0174(): 

```
 public void testItem_0174()
  {
    rc_BigDecimal = (new BigDecimal("3.2E+2")).movePointRight(0);
    Assert.assertEquals("320", rc_BigDecimal.toString());
  }
```

The test is expecting  `(new BigDecimal("3.2E+2")).movePointRight(0)` to return `320`, but it is returning 3[.2E+2]. -- So this reiterates what Pete said in https://github.com/AdoptOpenJDK/openjdk-systemtest/issues/259#issuecomment-506403280 " the numbers are the same, just represented differently". 

Is the BigDecimal#movePointRight(n) API is behaving differently in JDK13?

**Comment by pshipton** [comment]
Different tests were failing in each run, the results were not consistent. 
i.e. it seems that `(new BigDecimal("3.2E+2")).movePointRight(0)` doesn't always return `3[.2E+2]`, as this test didn't fail in every run. Unless the test suite is doing something that would explain this?
Perhaps it is a bug in the Java 13 BigDecimal code.

**Comment by DanHeidinga** [comment]
Looks like a deliberate change in JDK13 in `movePointRight()`:

JDK 13:
https://github.com/ibmruntimes/openj9-openjdk-jdk13/blob/0bcd1d5bd66ca25fba18a7bbf5003a395470d4fe/src/java.base/share/classes/java/math/BigDecimal.java#L2903-L2909

JDK 12:
https://github.com/ibmruntimes/openj9-openjdk-jdk12/blob/b26359aebe7ec913c0abdac75fb6abe21ed28cf0/src/java.base/share/classes/java/math/BigDecimal.java#L2901-L2905

https://bugs.openjdk.java.net/browse/JDK-8183912

The tests will need to be updated to stop using `.movePointRight(0)` as it now just returns the receiver

**Comment by Mesbah-Alam** [comment]
Thanks for finding this @DanHeidinga. I'll update the tests.

**Comment by Mesbah-Alam** [comment]
`movePointLeft()` was also updated in JDK13. So, I'll update the tests that use that API as well. 

JDK13: 
https://github.com/ibmruntimes/openj9-openjdk-jdk12/blob/b26359aebe7ec913c0abdac75fb6abe21ed28cf0/src/java.base/share/classes/java/math/BigDecimal.java#L2879

JDK12: 
https://github.com/ibmruntimes/openj9-openjdk-jdk12/blob/b26359aebe7ec913c0abdac75fb6abe21ed28cf0/src/java.base/share/classes/java/math/BigDecimal.java#L2879

**Comment by Mesbah-Alam** [comment]
In JDK13: 

` rc_BigDecimal = (new BigDecimal("00.0E+2147483647")).movePointLeft(0); ` returns `00.0E+2147483646` ; when `00.0E+2147483647` (the same value as passed in) was expected. 

@DanHeidinga  - is this a bug? Or should we update the test to expect `00.0E+2147483646` ?

**Comment by pshipton** [comment]
This seems expected behavior.

`new BigDecimal("00.0E+2147483647")` returns `0E+2147483646`

**Comment by Mesbah-Alam** [comment]
@pshipton thanks for clarifying. I'll update the test accordingly.

**Comment by pshipton** [comment]
Ran the system tests on OpenJ9 plinux and they passed with this change.
