### ISSUE TITLE
Another mauve failure related to SecurityManager

### ISSUE THREAD

**Issue by pshipton** [AdoptOpenJDK/openjdk-systemtest#263]
https://ci.eclipse.org/openj9/job/Test_openjdk12_j9_sanity.system_ppc64le_linux_Nightly/37
MauveMultiThreadLoadTest_OpenJ9_0
```
LT  00:11:58.789 - First failure detected by thread: load-2. Not creating dumps as no dump generation is requested for this load test
LT  00:11:58.796 - Test failed
LT    Failure num.  = 1
LT    Test number   = 3589
LT    Test details  = 'Mauve[gnu.testlet.javax.net.ssl.SSLContext.TestDefaultInit]'
LT    Suite number  = 0
LT    Thread number = 2
LT  >>> Captured test output >>>
LT  PASS: gnu.testlet.javax.net.ssl.SSLContext.TestDefaultInit (number 0)
LT  Test failed:
LT  java.lang.ExceptionInInitializerError
LT  	at java.base/java.lang.J9VMInternals.ensureError(J9VMInternals.java:193)
LT  	at java.base/java.lang.J9VMInternals.recordInitializationFailure(J9VMInternals.java:182)
LT  	at java.base/sun.security.provider.X509Factory.commitEvent(X509Factory.java:773)
LT  	at java.base/sun.security.provider.X509Factory.engineGenerateCertificate(X509Factory.java:108)
LT  	at java.base/java.security.cert.CertificateFactory.generateCertificate(CertificateFactory.java:355)
LT  	at java.base/sun.security.provider.JavaKeyStore.engineLoad(JavaKeyStore.java:761)
LT  	at java.base/sun.security.util.KeyStoreDelegator.engineLoad(KeyStoreDelegator.java:243)
LT  	at java.base/java.security.KeyStore.load(KeyStore.java:1472)
LT  	at java.base/sun.security.ssl.TrustStoreManager$TrustAnchorManager.loadKeyStore(TrustStoreManager.java:365)
LT  	at java.base/sun.security.ssl.TrustStoreManager$TrustAnchorManager.getTrustedCerts(TrustStoreManager.java:313)
LT  	at java.base/sun.security.ssl.TrustStoreManager.getTrustedCerts(TrustStoreManager.java:55)
LT  	at java.base/sun.security.ssl.TrustManagerFactoryImpl.engineInit(TrustManagerFactoryImpl.java:49)
LT  	at java.base/javax.net.ssl.TrustManagerFactory.init(TrustManagerFactory.java:278)
LT  	at java.base/sun.security.ssl.SSLContextImpl.engineInit(SSLContextImpl.java:88)
LT  	at java.base/javax.net.ssl.SSLContext.init(SSLContext.java:295)
LT  	at gnu.testlet.javax.net.ssl.SSLContext.TestDefaultInit.test(TestDefaultInit.java:62)
LT  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
LT  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
LT  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
LT  	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
LT  	at net.adoptopenjdk.loadTest.adaptors.MauveAdaptor.executeTest(MauveAdaptor.java:74)
LT  	at net.adoptopenjdk.loadTest.LoadTestRunner$2.run(LoadTestRunner.java:182)
LT  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
LT  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
LT  	at java.base/java.lang.Thread.run(Thread.java:831)
LT  Caused by: java.security.AccessControlException: access denied: ("java.util.logging.LoggingPermission" "control")
LT  	at gnu.testlet.java.util.logging.Logger.TestSecurityManager.checkPermission(TestSecurityManager.java:48)
LT  	at java.logging/java.util.logging.LogManager.checkPermission(LogManager.java:2432)
LT  	at java.logging/java.util.logging.Logger.setParent(Logger.java:2378)
LT  	at java.logging/java.util.logging.LogManager$6.run(LogManager.java:1259)
LT  	at java.base/java.security.AccessController.doPrivileged(AccessController.java:647)
LT  	at java.logging/java.util.logging.LogManager.doSetParent(LogManager.java:1256)
LT  	at java.logging/java.util.logging.LogManager$LoggerContext.addLocalLogger(LogManager.java:826)
LT  	at java.logging/java.util.logging.LogManager$LoggerContext.addLocalLogger(LogManager.java:755)
LT  	at java.logging/java.util.logging.LogManager$SystemLoggerContext.demandLogger(LogManager.java:935)
LT  	at java.logging/java.util.logging.LogManager.demandSystemLogger(LogManager.java:556)
LT  	at java.logging/java.util.logging.LogManager$LoggingProviderAccess.demandLoggerFor(LogManager.java:2710)
LT  	at java.logging/sun.util.logging.internal.LoggingProviderImpl.lambda$demandJULLoggerFor$0(LoggingProviderImpl.java:414)
LT  	at sun.util.logging.internal.LoggingProviderImpl$$Lambda$134.00000000E4029460.run(Unknown Source)
LT  	at java.base/java.security.AccessController.doPrivileged(AccessController.java:842)
LT  	at java.logging/sun.util.logging.internal.LoggingProviderImpl.demandJULLoggerFor(LoggingProviderImpl.java:415)
LT  	at java.logging/sun.util.logging.internal.LoggingProviderImpl.demandLoggerFor(LoggingProviderImpl.java:436)
LT  	at java.base/jdk.internal.logger.DefaultLoggerFinder.getLogger(DefaultLoggerFinder.java:157)
LT  	at java.base/jdk.internal.logger.LazyLoggers.lambda$getLoggerFromFinder$0(LazyLoggers.java:392)
LT  	at jdk.internal.logger.LazyLoggers$$Lambda$129.00000000E401A4D0.run(Unknown Source)
LT  	at java.base/java.security.AccessController.doPrivileged(AccessController.java:842)
LT  	at java.base/jdk.internal.logger.LazyLoggers.getLoggerFromFinder(LazyLoggers.java:391)
LT  	at java.base/jdk.internal.logger.LazyLoggers.getLazyLogger(LazyLoggers.java:444)
LT  	at java.base/jdk.internal.logger.LazyLoggers.getLogger(LazyLoggers.java:414)
LT  	at java.base/java.lang.System.getLogger(System.java:1062)
LT  	at java.base/jdk.internal.event.EventHelper.<clinit>(EventHelper.java:45)
LT  	... 23 more
LT  <<<
```

**Comment by pshipton** [comment]
@Mesbah-Alam

**Comment by Mesbah-Alam** [comment]
I'll close this issue at this point since the sub-tests have been permanently disabled.
