### ISSUE TITLE
Mauve issue related to SecurityManager

### ISSUE THREAD

**Issue by pshipton** [AdoptOpenJDK/openjdk-systemtest#271]
Not the problem is with tests that enable the SecurityManager, not with the tests that fail.
See also #263

https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_sanity.system_ppc64le_linux_Nightly/59/
```
LT  00:13:54.456 - First failure detected by thread: load-2. Not creating dumps as no dump generation is requested for this load test
LT  00:13:54.461 - Test failed
LT    Failure num.  = 1
LT    Test number   = 3050
LT    Test details  = 'Mauve[gnu.testlet.java.net.URLConnection.getRequestProperties]'
LT    Suite number  = 0
LT    Thread number = 2
LT  >>> Captured test output >>>
LT  Test failed:
LT  java.lang.ExceptionInInitializerError
LT  	at java.base/java.lang.J9VMInternals.ensureError(J9VMInternals.java:193)
LT  	at java.base/java.lang.J9VMInternals.recordInitializationFailure(J9VMInternals.java:182)
LT  	at java.base/sun.net.www.protocol.http.Handler.openConnection(Handler.java:62)
LT  	at java.base/sun.net.www.protocol.http.Handler.openConnection(Handler.java:57)
LT  	at java.base/java.net.URL.openConnection(URL.java:1051)
LT  	at gnu.testlet.java.net.URLConnection.getRequestProperties.test(getRequestProperties.java:43)
LT  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
LT  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
LT  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
LT  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
LT  	at net.adoptopenjdk.loadTest.adaptors.MauveAdaptor.executeTest(MauveAdaptor.java:74)
LT  	at net.adoptopenjdk.loadTest.LoadTestRunner$2.run(LoadTestRunner.java:182)
LT  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
LT  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
LT  	at java.base/java.lang.Thread.run(Thread.java:831)
LT  Caused by: java.security.AccessControlException: access denied: ("java.util.logging.LoggingPermission" "control")
LT  	at gnu.testlet.java.util.logging.Logger.TestSecurityManager.checkPermission(TestSecurityManager.java:48)
LT  	at java.logging/java.util.logging.LogManager$LoggingProviderAccess.demandLoggerFor(LogManager.java:2707)
LT  	at java.logging/sun.util.logging.internal.LoggingProviderImpl.lambda$demandJULLoggerFor$0(LoggingProviderImpl.java:414)
LT  	at sun.util.logging.internal.LoggingProviderImpl$$Lambda$117.00000000D0093A30.run(Unknown Source)
LT  	at java.base/java.security.AccessController.doPrivileged(AccessController.java:842)
LT  	at java.logging/sun.util.logging.internal.LoggingProviderImpl.demandJULLoggerFor(LoggingProviderImpl.java:415)
LT  	at java.logging/sun.util.logging.internal.LoggingProviderImpl.demandLoggerFor(LoggingProviderImpl.java:436)
LT  	at java.base/jdk.internal.logger.DefaultLoggerFinder.getLogger(DefaultLoggerFinder.java:157)
LT  	at java.base/jdk.internal.logger.LazyLoggers.lambda$getLoggerFromFinder$0(LazyLoggers.java:392)
LT  	at jdk.internal.logger.LazyLoggers$$Lambda$112.00000000D0092300.run(Unknown Source)
LT  	at java.base/java.security.AccessController.doPrivileged(AccessController.java:842)
LT  	at java.base/jdk.internal.logger.LazyLoggers.getLoggerFromFinder(LazyLoggers.java:391)
LT  	at java.base/jdk.internal.logger.LazyLoggers.getLazyLogger(LazyLoggers.java:444)
LT  	at java.base/sun.util.logging.PlatformLogger.getLogger(PlatformLogger.java:297)
LT  	at java.base/sun.net.www.protocol.http.HttpURLConnection.<clinit>(HttpURLConnection.java:431)
LT  	... 13 more
```

**Comment by pshipton** [comment]
@Mesbah-Alam

**Comment by Mesbah-Alam** [comment]
Just an fyi.. 

5x Grinder passes 100% on the test: https://hyc-runtimes-jenkins.swg-devops.com/view/Test_system/job/Grinder/2546/tapResults/

**Comment by Mesbah-Alam** [comment]
A 5x Grinder run on the same machine on which the build failed has 100% pass rate as well: https://ci.eclipse.org/openj9/view/Test/job/Test-Grinder/406/tapResults/

**Comment by pshipton** [comment]
This is a timing problem. If some other test installs a SecurityManager at the same time as URLConnection.getRequestProperties is running, the failure is caused. My recollection is we excluded all the tests which set a SecurityManager, but it seems something was missed. 

Search for `System.setSecurityManager`.
I don't think this is possible, but just in case `-Djava.security.manager=`

**Comment by pshipton** [comment]
Also note we run this test across all platforms every night at OpenJ9, and this doesn't typically fail, so it's going to be a rare occurrence.

**Comment by Mesbah-Alam** [comment]
Doing a `grep -rnw . -e System.setSecurityManager` on Mauve source reveals a few hits: 

```
./gnu/testlet/java/util/logging/Handler/TestSecurityManager.java:69:    System.setSecurityManager(this);
./gnu/testlet/java/util/logging/Handler/TestSecurityManager.java:75:    System.setSecurityManager(oldManager);
./gnu/testlet/java/util/logging/Logger/TestSecurityManager.java:69:    System.setSecurityManager(this);
./gnu/testlet/java/util/logging/Logger/TestSecurityManager.java:75:    System.setSecurityManager(oldManager);
./gnu/testlet/java/security/ProtectionDomain/Implies.java:64:    System.setSecurityManager(new SecurityManager());
./gnu/testlet/java/security/Policy/setPolicy.java:63:      System.setSecurityManager(this);
./gnu/testlet/java/security/Policy/Security.java:56:    System.setSecurityManager(new SecurityManager()
./gnu/testlet/java/lang/management/BadGuy.java:76:    System.setSecurityManager(this);
./gnu/testlet/java/lang/management/BadGuy.java:84:    System.setSecurityManager(oldManager);
./gnu/testlet/java/lang/System/security.java:297:	// throwpoint: java.lang.System-setSecurityManager
./gnu/testlet/java/lang/System/security.java:301:	  System.setSecurityManager(sm);
./gnu/testlet/java/lang/Integer/getInteger.java:86:              System.setSecurityManager(this);
./gnu/testlet/java/lang/Integer/getInteger.java:108:          System.setSecurityManager(old_security_manager); 
./gnu/testlet/java/lang/Thread/security10.java:60:        System.setSecurityManager(secman);
./gnu/testlet/java/lang/Thread/security10.java:72:    System.setSecurityManager(new MySecurityManager());
./gnu/testlet/TestSecurityManager.java:237:    System.setSecurityManager(this);
./gnu/testlet/TestSecurityManager.java:251:    System.setSecurityManager(oldManager);
```

Doing a `grep -rnw . -e '-Djava.security.manager='` finds no match.

**Comment by Mesbah-Alam** [comment]
The following PR excluded the tests that usesSecurityManager : https://github.com/AdoptOpenJDK/openjdk-systemtest/pull/241/files

It does not include the failing test `gnu.testlet.java.net.URLConnection.getRequestProperties` - it should also be excluded.

**Comment by Mesbah-Alam** [comment]
Looking at the exception trace of the failure in this current issue, the test ended up making a reference to security manager after calling `java.base/java.net.URL.openConnection(URL.java:1051)` --  

From gnu.testlet.java.net.URLConnection.getRequestProperties.test(getRequestProperties.java:43): 

```
harness.checkPoint("getRequestProperties");
        URL url = new URL("http://foo.bar/blah/blah");
        URLConnection c = url.openConnection();

```
This makes me wonder, should we exclude all tests that make a call to `url.openConnection()` from running in Multi-threaded Mauve load as well? @pshipton

**Comment by Mesbah-Alam** [comment]
Doing a `grep -rnw . -e 'openConnection'` on the Mauve repository yields the following hits: 

```
./gnu/testlet/java/net/URLConnection/post.java:34:	HttpURLConnection conn = (HttpURLConnection) url.openConnection();
./gnu/testlet/java/net/URLConnection/getHeaderFields.java:40:	URLConnection conn = url.openConnection();
./gnu/testlet/java/net/URLConnection/Jar.java:49:            connection = (JarURLConnection) url.openConnection();
./gnu/testlet/java/net/URLConnection/URLConnectionTest.java:42:	  _url.openConnection();
./gnu/testlet/java/net/URLConnection/URLConnectionTest.java:52:      URLConnection conn = url.openConnection();
./gnu/testlet/java/net/URLConnection/URLConnectionTest.java:99:      URLConnection conn = url.openConnection();
./gnu/testlet/java/net/URLConnection/URLConnectionTest.java:125:      URLConnection conn = url.openConnection();
./gnu/testlet/java/net/URLConnection/URLConnectionTest.java:168:      URLConnection conn = url.openConnection();
./gnu/testlet/java/net/URLConnection/URLConnectionTest.java:187:      URLConnection conn = url.openConnection();
./gnu/testlet/java/net/URLConnection/URLConnectionTest.java:213:      URLConnection conn = url.openConnection();
./gnu/testlet/java/net/URLConnection/URLConnectionTest.java:233:      URLConnection conn = url.openConnection();
./gnu/testlet/java/net/URLConnection/URLConnectionTest.java:260:      URLConnection conn = url.openConnection();
./gnu/testlet/java/net/URLConnection/URLConnectionTest.java:289:      URLConnection conn = url.openConnection();
./gnu/testlet/java/net/URLConnection/URLConnectionTest.java:446:      HttpURLConnection conn = (HttpURLConnection) url.openConnection();
./gnu/testlet/java/net/URLConnection/getPermission.java:53:	URLConnection uc = u.openConnection();
./gnu/testlet/java/net/URLConnection/getPermission.java:68:	URLConnection uc = u.openConnection();
./gnu/testlet/java/net/URLConnection/getPermission.java:84:	URLConnection uc = u.openConnection();
./gnu/testlet/java/net/URLConnection/getPermission.java:100:	URLConnection uc = u.openConnection();
./gnu/testlet/java/net/URLConnection/Http.java:33:	URLConnection conn = url.openConnection();
./gnu/testlet/java/net/URLConnection/getRequestProperties.java:43:        URLConnection c = url.openConnection();
./gnu/testlet/java/net/URLStreamHandler/Except.java:40:		protected URLConnection openConnection(URL u)
./gnu/testlet/java/net/URL/MyURLStreamHandler.java:38:  protected URLConnection openConnection(URL u) throws IOException { return (URLConnection)new Object(); }
./gnu/testlet/java/net/URL/security.java:106:    public URLConnection openConnection(URL url) throws IOException
./gnu/testlet/java/net/URL/URLTest.java:198:		harness.checkPoint("openConnection");
./gnu/testlet/java/net/URL/URLTest.java:202:			URLConnection conn = url.openConnection();
./gnu/testlet/java/net/URL/URLTest.java:205:				harness.fail("openConnection returned null");
./gnu/testlet/java/net/URLClassLoader/security.java:104:          protected URLConnection openConnection(URL u) throws IOException
./gnu/testlet/java/net/HttpURLConnection/illegalStateException.java:43:        HttpURLConnection conn = (HttpURLConnection) url.openConnection();
./gnu/testlet/java/net/HttpURLConnection/reuseConnection.java:334:        HttpURLConnection conn = (HttpURLConnection) url.openConnection();
./gnu/testlet/java/net/HttpURLConnection/reuseConnection.java:354:        conn = (HttpURLConnection) url.openConnection();
./gnu/testlet/java/net/HttpURLConnection/reuseConnection.java:377:        conn = (HttpURLConnection) url.openConnection();
./gnu/testlet/java/net/HttpURLConnection/reuseConnection.java:397:        conn = (HttpURLConnection) url.openConnection();
./gnu/testlet/java/net/HttpURLConnection/reuseConnection.java:453:        HttpURLConnection conn = (HttpURLConnection) url.openConnection();
./gnu/testlet/java/net/HttpURLConnection/reuseConnection.java:472:        conn = (HttpURLConnection) url.openConnection();
./gnu/testlet/java/net/HttpURLConnection/reuseConnection.java:505:        HttpURLConnection conn = (HttpURLConnection) url.openConnection();
./gnu/testlet/java/net/HttpURLConnection/reuseConnection.java:524:        conn = (HttpURLConnection) url.openConnection();
./gnu/testlet/java/net/HttpURLConnection/nullPointerException.java:42:        HttpURLConnection conn = (HttpURLConnection) url.openConnection();
./gnu/testlet/java/net/HttpURLConnection/requestPropertiesTest.java:63:        HttpURLConnection conn = (HttpURLConnection) url.openConnection();
./gnu/testlet/java/net/HttpURLConnection/requestPropertiesTest.java:123:        HttpURLConnection conn = (HttpURLConnection) url.openConnection();
./gnu/testlet/java/net/HttpURLConnection/fileNotFound.java:45:        HttpURLConnection conn = (HttpURLConnection) url.openConnection();
./gnu/testlet/java/net/HttpURLConnection/getRequestProperty.java:42:        HttpURLConnection conn = (HttpURLConnection) url.openConnection();
./gnu/testlet/java/net/HttpURLConnection/postHeaders.java:128:        HttpURLConnection conn = (HttpURLConnection) url.openConnection();
./gnu/testlet/java/net/HttpURLConnection/responseCodeTest.java:122:        HttpURLConnection conn = (HttpURLConnection) url.openConnection();
./gnu/testlet/java/net/HttpURLConnection/getOutputStream.java:45:        HttpURLConnection conn = (HttpURLConnection) url.openConnection();
./gnu/testlet/java/net/HttpURLConnection/timeout.java:164:        HttpURLConnection conn = (HttpURLConnection) url.openConnection();
./gnu/testlet/java/net/HttpURLConnection/timeout.java:184:        conn = (HttpURLConnection) url.openConnection();
./gnu/testlet/java/net/HttpURLConnection/timeout.java:198:        conn = (HttpURLConnection) url.openConnection();
./gnu/testlet/java/net/HttpURLConnection/timeout.java:234:        HttpURLConnection conn = (HttpURLConnection) url.openConnection();
./gnu/testlet/java/net/HttpURLConnection/responseHeadersTest.java:120:        HttpURLConnection conn = (HttpURLConnection) url.openConnection();
./gnu/testlet/java/net/HttpURLConnection/responseHeadersTest.java:277:        HttpURLConnection conn = (HttpURLConnection) url.openConnection();
./gnu/testlet/javax/swing/text/html/HTML/ElementTagAttributeTest.java:66:    URLConnection connection = url.openConnection();
```

I've gone through the above and made sure we exclude the tests from the multi-threaded mauve load.

**Comment by pshipton** [comment]
@Mesbah-Alam the tests that call `url.openConnection()` shouldn't need to be excluded. They should work fine when no other currently running test is installing a SecurityManager. 

getRequestProperties() shouldn't need to be excluded.

The test excluded via #263 (testlet.javax.net.ssl.SSLContext.TestDefaultInit) shouldn't need to be excluded either. Not sure if there were others.
