### ISSUE TITLE
Another mauve failure related to SecurityManager

### ISSUE THREAD

**Issue by JasonFengJ9** [AdoptOpenJDK/openjdk-systemtest#275]
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_sanity.system_ppc64le_linux_Nightly/59/tapResults/

```
LT  00:13:54.456 - First failure detected by thread: load-2. Not creating dumps as no dump generation is requested for this load test
LT  00:13:54.461 - Test failed
LT    Failure num.  = 1
LT    Test number   = 3050
LT    Test details  = 'Mauve[gnu.testlet.java.net.URLConnection.getRequestProperties]'
LT    Suite number  = 0
LT    Thread number = 2
LT  >>> Captured test output >>>
LT  Test failed:
LT  java.lang.ExceptionInInitializerError
LT  	at java.base/java.lang.J9VMInternals.ensureError(J9VMInternals.java:193)
LT  	at java.base/java.lang.J9VMInternals.recordInitializationFailure(J9VMInternals.java:182)
LT  	at java.base/sun.net.www.protocol.http.Handler.openConnection(Handler.java:62)
LT  	at java.base/sun.net.www.protocol.http.Handler.openConnection(Handler.java:57)
LT  	at java.base/java.net.URL.openConnection(URL.java:1051)
LT  	at gnu.testlet.java.net.URLConnection.getRequestProperties.test(getRequestProperties.java:43)
LT  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
LT  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
LT  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
LT  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
LT  	at net.adoptopenjdk.loadTest.adaptors.MauveAdaptor.executeTest(MauveAdaptor.java:74)
LT  	at net.adoptopenjdk.loadTest.LoadTestRunner$2.run(LoadTestRunner.java:182)
LT  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
LT  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
LT  	at java.base/java.lang.Thread.run(Thread.java:831)
LT  Caused by: java.security.AccessControlException: access denied: ("java.util.logging.LoggingPermission" "control")
LT  	at gnu.testlet.java.util.logging.Logger.TestSecurityManager.checkPermission(TestSecurityManager.java:48)
LT  	at java.logging/java.util.logging.LogManager$LoggingProviderAccess.demandLoggerFor(LogManager.java:2707)
LT  	at java.logging/sun.util.logging.internal.LoggingProviderImpl.lambda$demandJULLoggerFor$0(LoggingProviderImpl.java:414)
LT  	at sun.util.logging.internal.LoggingProviderImpl$$Lambda$117.00000000D0093A30.run(Unknown Source)
LT  	at java.base/java.security.AccessController.doPrivileged(AccessController.java:842)
LT  	at java.logging/sun.util.logging.internal.LoggingProviderImpl.demandJULLoggerFor(LoggingProviderImpl.java:415)
LT  	at java.logging/sun.util.logging.internal.LoggingProviderImpl.demandLoggerFor(LoggingProviderImpl.java:436)
LT  	at java.base/jdk.internal.logger.DefaultLoggerFinder.getLogger(DefaultLoggerFinder.java:157)
LT  	at java.base/jdk.internal.logger.LazyLoggers.lambda$getLoggerFromFinder$0(LazyLoggers.java:392)
LT  	at jdk.internal.logger.LazyLoggers$$Lambda$112.00000000D0092300.run(Unknown Source)
LT  	at java.base/java.security.AccessController.doPrivileged(AccessController.java:842)
LT  	at java.base/jdk.internal.logger.LazyLoggers.getLoggerFromFinder(LazyLoggers.java:391)
LT  	at java.base/jdk.internal.logger.LazyLoggers.getLazyLogger(LazyLoggers.java:444)
LT  	at java.base/sun.util.logging.PlatformLogger.getLogger(PlatformLogger.java:297)
LT  	at java.base/sun.net.www.protocol.http.HttpURLConnection.<clinit>(HttpURLConnection.java:431)
LT  	... 13 more
LT  <<<
```

fyi: @Mesbah-Alam

**Comment by pshipton** [comment]
Dup of #271
