### ISSUE TITLE
SC_Softmx_UpDown incorrectly using module java.transaction

### ISSUE THREAD

**Issue by hangshao0** [AdoptOpenJDK/openjdk-systemtest#324]
I was running SC_Softmx_UpDown on Java 11. The job failed at step 16:

```
STF 14:37:02.367 - +------ Step 14 - Run a third workload after the cache size has been decreased
STF 14:37:02.367 - | Start background process
STF 14:37:02.367 - |   Program:     /home/jenkins/workspace/Test_openjdk11_j9_extended.system_ppc64le_linux_xl_Personal/openjdkbinary/j2sdk-image/bin/java
STF 14:37:02.367 - |   Mnemonic:    jvm3
STF 14:37:02.367 - |   Echo:        ECHO_OFF
STF 14:37:02.367 - |   Expectation: NON_ZERO_EXIT [0, 1] within 30m
STF 14:37:02.367 - |
STF 14:37:02.368 - Running command: /home/jenkins/workspace/Test_openjdk11_j9_extended.system_ppc64le_linux_xl_Personal/openjdkbinary/j2sdk-image/bin/java -Xshareclasses:name=SCC_SysTest_Workload_Cache,cacheDir=/home/jenkins/workspace/Test_openjdk11_j9_extended.system_ppc64le_linux_xl_Personal/openjdk-tests/TKG/test_output_15809311893397/SC_Softmx_UpDown_0/20200205-143629-SharedClassesWorkloadTest_Softmx_IncreaseDecrease/results/cache,verboseIO --add-modules=java.rmi,java.transaction,java.corba -Xnocompressedrefs -classpath /home/jenkins/workspace/Test_openjdk11_j9_extended.system_ppc64le_linux_xl_Personal/jvmtest/system/stf/stf.load/bin:/home/jenkins/workspace/Test_openjdk11_j9_extended.system_ppc64le_linux_xl_Personal/jvmtest/system/stf/stf.core/bin:/home/jenkins/workspace/Test_openjdk11_j9_extended.system_ppc64le_linux_xl_Personal/jvmtest/system/systemtest_prereqs/log4j-2.3/log4j-api-2.3.jar:/home/jenkins/workspace/Test_openjdk11_j9_extended.system_ppc64le_linux_xl_Personal/jvmtest/system/systemtest_prereqs/log4j-2.3/log4j-core-2.3.jar:/home/jenkins/workspace/Test_openjdk11_j9_extended.system_ppc64le_linux_xl_Personal/jvmtest/system/systemtest_prereqs/junit-4.12/junit-4.12.jar:/home/jenkins/workspace/Test_openjdk11_j9_extended.system_ppc64le_linux_xl_Personal/jvmtest/system/systemtest_prereqs/junit-4.12/hamcrest-core-1.3.jar:/home/jenkins/workspace/Test_openjdk11_j9_extended.system_ppc64le_linux_xl_Personal/jvmtest/system/openjdk-systemtest/openjdk.test.classloading/bin net.adoptopenjdk.loadTest.LoadTest -resultsDir /home/jenkins/workspace/Test_openjdk11_j9_extended.system_ppc64le_linux_xl_Personal/openjdk-tests/TKG/test_output_15809311893397/SC_Softmx_UpDown_0/20200205-143629-SharedClassesWorkloadTest_Softmx_IncreaseDecrease/results -resultsPrefix 14.jvm3. -abortIfOutOfMemory false -dumpRequested false -reportFailureLimit 1 -abortAtFailureLimit 10 -maxTotalLogFileSpace 200M -maxSingleLogSize 1/25 -suite.classloading.threadCount 7 -suite.classloading.inventoryFile /home/jenkins/workspace/Test_openjdk11_j9_extended.system_ppc64le_linux_xl_Personal/openjdk-tests/TKG/test_output_15809311893397/SC_Softmx_UpDown_0/20200205-143629-SharedClassesWorkloadTest_Softmx_IncreaseDecrease/results/14.jvm3.inventory/openjdk.test.load/config/inventories/classloading/classloading.xml -suite.classloading.inventoryExcludeFile none -suite.classloading.totalNumberTests 500 -suite.classloading.selection random -suite.classloading.seed -1 -suite.classloading.repeatCount 1 -suite.classloading.thinkingTime 0ms..0ms
STF 14:37:02.368 - Redirecting stderr to /home/jenkins/workspace/Test_openjdk11_j9_extended.system_ppc64le_linux_xl_Personal/openjdk-tests/TKG/test_output_15809311893397/SC_Softmx_UpDown_0/20200205-143629-SharedClassesWorkloadTest_Softmx_IncreaseDecrease/results/14.jvm3.stderr
STF 14:37:02.368 - Redirecting stdout to /home/jenkins/workspace/Test_openjdk11_j9_extended.system_ppc64le_linux_xl_Personal/openjdk-tests/TKG/test_output_15809311893397/SC_Softmx_UpDown_0/20200205-143629-SharedClassesWorkloadTest_Softmx_IncreaseDecrease/results/14.jvm3.stdout
STF 14:37:02.369 - 
STF 14:37:02.369 - +------ Step 15 - Wait for processes to complete
STF 14:37:02.369 - | Wait for processes to meet expectations
STF 14:37:02.369 - |   Processes: [jvm3]
STF 14:37:02.369 - |
STF 14:37:02.369 - Monitoring processes: jvm3
STF 14:37:02.493 - Monitoring Report Summary:
STF 14:37:02.493 -   o Process jvm3 ended with the expected exit code (1)
STF 14:37:02.494 - 
STF 14:37:02.494 - +------ Step 16 - Checking for output indicating failure to write to cache
STF 14:37:02.494 - | Count file matches
STF 14:37:02.494 - |   TargetFile:    /home/jenkins/workspace/Test_openjdk11_j9_extended.system_ppc64le_linux_xl_Personal/openjdk-tests/TKG/test_output_15809311893397/SC_Softmx_UpDown_0/20200205-143629-SharedClassesWorkloadTest_Softmx_IncreaseDecrease/results/14.jvm3.stderr
STF 14:37:02.494 - |   SearchStrings: ["Failed to store class"]
STF 14:37:02.494 - |
**FAILED** at step 16 (Checking for output indicating failure to write to cache). Expected return value=0 Actual=0 at /home/jenkins/workspace/Test_openjdk11_j9_extended.system_ppc64le_linux_xl_Personal/openjdk-tests/TKG/../TKG/test_output_15809311893397/SC_Softmx_UpDown_0/20200205-143629-SharedClassesWorkloadTest_Softmx_IncreaseDecrease/execute.pl line 600.
STF 14:37:02.794 - **FAILED** execute script failed. Expected return value=0 Actual=1
```

"14.jvm3.stderr" shows that step 14 failed to startup at a very early stage due to 
```
java.lang.module.FindException: Module java.transaction not found
	at java.base/java.lang.module.Resolver.findFail(Resolver.java:877)
	at java.base/java.lang.module.Resolver.resolve(Resolver.java:128)
	at java.base/java.lang.module.Configuration.resolveAndBind(Configuration.java:315)
	at java.base/java.lang.module.ModuleDescriptor$1.resolveAndBind(ModuleDescriptor.java:2693)
	at java.base/jdk.internal.module.ModuleBootstrap.boot(ModuleBootstrap.java:354)
	at java.base/java.lang.ClassLoader.initializeClassLoaders(ClassLoader.java:211)
	at java.base/java.lang.Thread.initialize(Thread.java:430)
	at java.base/java.lang.Thread.<init>(Thread.java:155)
```

Step 14 is using `--add-modules=java.rmi,java.transaction` in the command line. However, this module java.transaction is already removed by https://openjdk.java.net/jeps/320 in Java 11.

**Comment by hangshao0** [comment]
@Mesbah-Alam

**Comment by Mesbah-Alam** [comment]
@hangshao0 - I am a bit confused, if `java.transaction` module has been removed in JDK 11, why is the test working fine in the internal jdk11 openj9 builds? Test_openjdk11_j9_extended.system_ppc64le_linux_Nightly/293/consoleText

**Comment by Mesbah-Alam** [comment]
I believe we had added the `--add-modules` option to add those deprecated modules before they became deprecated to make the test to work with jdk9. They should be gone now. I've updated the test to use in the third workload something very similar to what was use in the first and second workload and thus remove the use of `--add-module` : https://github.com/eclipse/openj9-systemtest/pull/111 . 

But the question remains as to why the test kept working on jdk11 (and up) and how @hangshao0 get it to fail.

**Comment by hangshao0** [comment]
I am looking at how thing fails on my side. Will update if I found out.

**Comment by hangshao0** [comment]
> I am looking at how things fail on my side. Will update if I found out.

It is caused by my change.

**Comment by Mesbah-Alam** [comment]
> It is caused by my change.

Does it mean something in your change has fixed something else in the SDK which resolved whatever the issue was that caused the test to keep passing on jdk11 even with reference to deprecated modules?  

Because with https://github.com/eclipse/openj9-systemtest/pull/111 - the dependency in deprecated modules will be gone.

**Comment by hangshao0** [comment]
Something with my change caused this test to fail on my side. This test still passes (without my change), even with `java.lang.module.FindException` mentioned here. But the `java.lang.module.FindException` should still be fixed, which you already have done.

**Comment by Mesbah-Alam** [comment]
Thanks. The issue can now be closed.
