### ISSUE TITLE
JMXConnector timeout processing unreliable in JLM tests

### ISSUE THREAD

**Issue by lumpfish** [AdoptOpenJDK/openjdk-systemtest#370]
The JLM ServerConnector.java file contains the code:
```
boolean connected = false;
int attempts = 0;
while (connected == false && attempts < 30) {        
	try {
		Message.logOut("Trying to connect using JMXConnectorFactory");
		connector = JMXConnectorFactory.connect(address);
		connected = true;
	} catch (IOException ie) {
		// If we didn't connect, keep trying - the JVM being monitored might not be 
		// ready to accept connections yet.
		try {           	  
			Thread.sleep(10000);
		} catch (InterruptedException e) {
			Message.logOut("The sleeping profiler was interrupted");
			e.printStackTrace();
		}
		Message.logOut("Monitored VM not ready at " + 
				DateFormat.getDateTimeInstance().format(new Date()) +
				" (attempt " + attempts + ").");
		Message.logOut("Wait 10 secs and trying again...");	
		attempts++;           	
		connected = false;

		if (attempts == 30) {
			Message.logOut("Failed to connect to Monitored VM after "
					+ "30 attempts - giving up.  IOException received is below:");	 
			ie.printStackTrace();        	  	  
		}
	} 
}
```
The intention appears to be to retry the connection every 5 seconds up to a maximum of 150 seconds (30 attempts).

However, in some failure scenarios the time taken for the connect call to fail can run into minutes (let's say 2 minutes), so that the total retry time is (30 * 120) + (30 * 5) = 62 minutes 30 seconds.  The timeout value for the process running the connect is typically 30 minutes, so the process is killed before the 30 attempts are complete.  This means the final `ie.printStackTrace` is never executed and the details of the failed connect are not available.

Here is an example log in this scenario- note the two minute or so gaps after the `Wait 5 secs` log lines and the lack of information about why the connection failed:
```
14:08:11  STF 13:08:10.890 - +------ Step 5 - Wait for the processes to complete
14:08:11  STF 13:08:10.890 - | Wait for processes to meet expectations
14:08:11  STF 13:08:10.890 - |   Processes: [LT1, CL1]
14:08:11  STF 13:08:10.890 - |
14:08:11  STF 13:08:10.890 - Monitoring processes: CL1 LT1
14:08:11  CL1 j> 2020/10/15 13:08:11.372 ServerURL=service:jmx:rmi:///jndi/rmi://localhost:1234/jmxrmi
14:08:17  CL1 j> 2020/10/15 13:08:17.394 Monitored VM not ready at Oct 15, 2020, 1:08:17 PM (attempt 0).
14:08:17  CL1 j> 2020/10/15 13:08:17.397 Wait 5 secs and trying again...
14:12:41  CL1 j> 2020/10/15 13:12:39.904 Monitored VM not ready at Oct 15, 2020, 1:12:39 PM (attempt 1).
14:12:41  CL1 j> 2020/10/15 13:12:39.904 Wait 5 secs and trying again...
14:13:14  STF 13:13:10.145 - Heartbeat: Process LT1 is still running
14:15:07  CL1 j> 2020/10/15 13:14:52.225 Monitored VM not ready at Oct 15, 2020, 1:14:52 PM (attempt 2).
14:15:07  CL1 j> 2020/10/15 13:14:52.227 Wait 5 secs and trying again...
14:17:15  CL1 j> 2020/10/15 13:17:04.704 Monitored VM not ready at Oct 15, 2020, 1:17:04 PM (attempt 3).
14:17:15  CL1 j> 2020/10/15 13:17:04.705 Wait 5 secs and trying again...
14:18:12  STF 13:18:10.277 - Heartbeat: Process LT1 is still running
14:19:21  CL1 j> 2020/10/15 13:19:17.185 Monitored VM not ready at Oct 15, 2020, 1:19:17 PM (attempt 4).
14:19:21  CL1 j> 2020/10/15 13:19:17.186 Wait 5 secs and trying again...
14:19:26  CL1 j> 2020/10/15 13:19:25.228 Monitored VM not ready at Oct 15, 2020, 1:19:25 PM (attempt 5).
14:19:26  CL1 j> 2020/10/15 13:19:25.228 Wait 5 secs and trying again...

14:21:49  CL1 j> 2020/10/15 13:21:37.505 Monitored VM not ready at Oct 15, 2020, 1:21:37 PM (attempt 6).
14:21:49  CL1 j> 2020/10/15 13:21:37.506 Wait 5 secs and trying again...

14:23:12  STF 13:23:10.085 - Heartbeat: Process LT1 is still running

14:23:52  CL1 j> 2020/10/15 13:23:49.824 Monitored VM not ready at Oct 15, 2020, 1:23:49 PM (attempt 7).
14:23:52  CL1 j> 2020/10/15 13:23:49.825 Wait 5 secs and trying again...

14:26:15  CL1 j> 2020/10/15 13:26:02.145 Monitored VM not ready at Oct 15, 2020, 1:26:02 PM (attempt 8).
14:26:15  CL1 j> 2020/10/15 13:26:02.146 Wait 5 secs and trying again...

14:28:23  STF 13:28:10.234 - Heartbeat: Process LT1 is still running
14:28:23  CL1 j> 2020/10/15 13:28:14.624 Monitored VM not ready at Oct 15, 2020, 1:28:14 PM (attempt 9).
14:28:23  CL1 j> 2020/10/15 13:28:14.624 Wait 5 secs and trying again...

14:30:31  CL1 j> 2020/10/15 13:30:26.945 Monitored VM not ready at Oct 15, 2020, 1:30:26 PM (attempt 10).
14:30:31  CL1 j> 2020/10/15 13:30:26.945 Wait 5 secs and trying again...

14:32:39  CL1 j> 2020/10/15 13:32:39.265 Monitored VM not ready at Oct 15, 2020, 1:32:39 PM (attempt 11).
14:32:39  CL1 j> 2020/10/15 13:32:39.266 Wait 5 secs and trying again...

14:33:13  STF 13:33:10.397 - Heartbeat: Process LT1 is still running

14:35:06  CL1 j> 2020/10/15 13:34:51.584 Monitored VM not ready at Oct 15, 2020, 1:34:51 PM (attempt 12).
14:35:06  CL1 j> 2020/10/15 13:34:51.585 Wait 5 secs and trying again...

14:37:14  CL1 j> 2020/10/15 13:37:03.909 Monitored VM not ready at Oct 15, 2020, 1:37:03 PM (attempt 13).
14:37:14  CL1 j> 2020/10/15 13:37:03.909 Wait 5 secs and trying again...
14:37:14  CL1 j> 2020/10/15 13:37:11.964 Monitored VM not ready at Oct 15, 2020, 1:37:11 PM (attempt 14).
14:37:14  CL1 j> 2020/10/15 13:37:11.965 Wait 5 secs and trying again...

14:38:11  STF 13:38:10.082 - Heartbeat: Process LT1 is still running
14:38:11  STF 13:38:11.084 - **FAILED** Process CL1 has timed out
14:40:12  CL1 j> 2020/10/15 13:39:24.386 Monitored VM not ready at Oct 15, 2020, 1:39:24 PM (attempt 15).
14:40:12  CL1 j> 2020/10/15 13:39:24.386 Wait 5 secs and trying again...
14:40:12  CL1 j> 2020/10/15 13:39:29.399 Monitored VM not ready at Oct 15, 2020, 1:39:29 PM (attempt 16).
14:40:12  CL1 j> 2020/10/15 13:39:29.400 Wait 5 secs and trying again...
14:40:12  CL1 j> 2020/10/15 13:39:34.404 Monitored VM not ready at Oct 15, 2020, 1:39:34 PM (attempt 17).
14:40:12  CL1 j> 2020/10/15 13:39:34.404 Wait 5 secs and trying again...
14:40:12  CL1 j> 2020/10/15 13:39:39.410 Monitored VM not ready at Oct 15, 2020, 1:39:39 PM (attempt 18).
14:40:12  CL1 j> 2020/10/15 13:39:39.410 Wait 5 secs and trying again...
14:40:12  CL1 j> 2020/10/15 13:39:44.416 Monitored VM not ready at Oct 15, 2020, 1:39:44 PM (attempt 19).
14:40:12  CL1 j> 2020/10/15 13:39:44.416 Wait 5 secs and trying again...
14:40:12  STF 13:40:11.101 - Monitoring Report Summary:
14:40:12  STF 13:40:11.101 -   o Process CL1 has timed out
14:40:12  STF 13:40:11.102 -   o Process LT1 ended sucessfully
14:40:12  STF 13:40:11.104 - Killing processes: CL1 LT1
14:40:12  STF 13:40:11.104 -   o Process CL1 is not running
14:40:12  STF 13:40:11.104 -   o Process LT1 is not running
14:40:12  **FAILED** at step 5 (Wait for the processes to complete). Expected return value=0 Actual=1 at /home/jenkins/workspace/Grinder/openjdk-tests/TKG/../TKG/test_output_1602767285252/TestJlmRemoteClassAuth_0/20201015-130805-TestJlmRemoteClassAuth/execute.pl line 174.
14:40:12  STF 13:40:11.483 - **FAILED** execute script failed. Expected return value=0 Actual=1
```

I've modified the code in this PR https://github.com/AdoptOpenJDK/openjdk-systemtest/pull/369 to abort the attempt to connect after 30 attempts or 5 minutes, whichever comes first, so that the test will always print the stack trace for the last failure attempt when it cannot connect.

Here is some sample output from the PR code:
```
14:55:09  STF 13:55:08.990 - +------ Step 5 - Wait for the processes to complete
14:55:09  STF 13:55:08.990 - | Wait for processes to meet expectations
14:55:09  STF 13:55:08.990 - |   Processes: [LT1, CL1]
14:55:09  STF 13:55:08.990 - |
14:55:09  STF 13:55:08.990 - Monitoring processes: CL1 LT1
14:55:09  CL1 j> 2020/10/15 13:55:09.474 ServerURL=service:jmx:rmi:///jndi/rmi://localhost:1234/jmxrmi
14:55:09  CL1 j> 2020/10/15 13:55:09.662 Attempting to connect
14:55:10  CL1 j> 2020/10/15 13:55:10.237 Monitored VM not ready at Oct 15, 2020, 1:55:10 PM (attempt 1, elapsed 531ms).
14:55:10  CL1 j> 2020/10/15 13:55:10.237 Waiting 5 secs and trying again...
14:55:16  CL1 j> 2020/10/15 13:55:15.238 Attempting to connect

14:59:39  CL1 j> 2020/10/15 13:59:34.265 Monitored VM not ready at Oct 15, 2020, 1:59:34 PM (attempt 2, elapsed 264601ms).
14:59:39  CL1 j> 2020/10/15 13:59:34.266 Waiting 5 secs and trying again...
14:59:39  CL1 j> 2020/10/15 13:59:39.267 Attempting to connect

15:00:13  STF 14:00:08.080 - Heartbeat: Process LT1 is still running

15:01:51  CL1 j> 2020/10/15 14:01:46.585 Failed to connect to Monitored VM after 3 attempts in 396 seconds - giving up.  Connection Exception received is below:
15:01:51  CL1 stderr java.rmi.ConnectException: Connection refused to host: 10.8.206.67; nested exception is: 
15:01:51  CL1 stderr 	java.net.ConnectException: Connection timed out
15:01:51  CL1 stderr 	at java.rmi/sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:623)
15:01:51  CL1 stderr 	at java.rmi/sun.rmi.transport.tcp.TCPChannel.createConnection(TCPChannel.java:209)
15:01:51  CL1 stderr 	at java.rmi/sun.rmi.transport.tcp.TCPChannel.newConnection(TCPChannel.java:196)
15:01:51  CL1 stderr 	at java.rmi/sun.rmi.server.UnicastRef.invoke(UnicastRef.java:132)
15:01:51  CL1 stderr 	at java.management.rmi/javax.management.remote.rmi.RMIServerImpl_Stub.newClient(RMIServerImpl_Stub.java:83)
15:01:51  CL1 stderr 	at java.management.rmi/javax.management.remote.rmi.RMIConnector.getConnection(RMIConnector.java:2105)
15:01:51  CL1 stderr 	at java.management.rmi/javax.management.remote.rmi.RMIConnector.connect(RMIConnector.java:321)
15:01:51  CL1 stderr 	at java.management/javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:270)
15:01:51  CL1 stderr 	at net.adoptopenjdk.test.jlm.remote.ServerConnector.getSecureServerConnection(ServerConnector.java:189)
15:01:51  CL1 stderr 	at net.adoptopenjdk.test.jlm.remote.ServerConnector.<init>(ServerConnector.java:81)
15:01:51  CL1 stderr 	at net.adoptopenjdk.test.jlm.remote.ClassProfiler.<init>(ClassProfiler.java:72)
15:01:51  CL1 stderr 	at net.adoptopenjdk.test.jlm.remote.ClassProfiler.main(ClassProfiler.java:89)
15:01:51  CL1 stderr Caused by: java.net.ConnectException: Connection timed out
15:01:51  CL1 stderr 	at java.base/sun.nio.ch.Net.connect0(Native Method)
15:01:51  CL1 stderr 	at java.base/sun.nio.ch.Net.connect(Net.java:574)
15:01:51  CL1 stderr 	at java.base/sun.nio.ch.Net.connect(Net.java:563)
15:01:51  CL1 stderr 	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:588)
15:01:51  CL1 stderr 	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:333)
15:01:51  CL1 stderr 	at java.base/java.net.Socket.connect(Socket.java:648)
15:01:51  CL1 stderr 	at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:290)
15:01:51  CL1 stderr 	at java.base/sun.security.ssl.SSLSocketImpl.<init>(SSLSocketImpl.java:149)
15:01:51  CL1 stderr 	at java.base/sun.security.ssl.SSLSocketFactoryImpl.createSocket(SSLSocketFactoryImpl.java:88)
15:01:51  CL1 stderr 	at java.rmi/javax.rmi.ssl.SslRMIClientSocketFactory.createSocket(SslRMIClientSocketFactory.java:121)
15:01:51  CL1 stderr 	at java.rmi/sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:617)
15:01:51  CL1 stderr 	... 11 more
15:01:51  CL1 stderr Exception in thread "main" java.lang.NullPointerException
15:01:51  CL1 stderr 	at java.management/java.lang.management.ManagementFactory.isInstanceOf(ManagementFactory.java:651)
15:01:51  CL1 stderr 	at java.management/java.lang.management.ManagementFactory.newPlatformMXBeanProxy(ManagementFactory.java:611)
15:01:51  CL1 stderr 	at net.adoptopenjdk.test.jlm.remote.ClassProfiler.getStatsViaProxy(ClassProfiler.java:117)
15:01:51  CL1 stderr 	at net.adoptopenjdk.test.jlm.remote.ClassProfiler.main(ClassProfiler.java:102)
15:01:51  STF 14:01:46.977 - **FAILED** Process CL1 ended with exit code (1) and not the expected exit code/s (0)
15:01:51  STF 14:01:46.978 - Monitoring Report Summary:
15:01:51  STF 14:01:46.978 -   o Process CL1 ended with exit code (1) and not the expected exit code/s (0)
15:01:51  STF 14:01:46.978 -   o Process LT1 is still running as expected
15:01:51  STF 14:01:46.978 - Killing processes: CL1 LT1

15:01:58  STF 14:01:57.994 -   o Process LT1 killed
15:01:58  STF 14:01:57.994 -   o Process CL1 is not running
15:01:58  **FAILED** at step 5 (Wait for the processes to complete). Expected return value=0 Actual=1 at /home/jenkins/workspace/Grinder/openjdk-tests/TKG/../TKG/test_output_16027701033819/TestJlmRemoteClassAuth_0/20201015-135503-TestJlmRemoteClassAuth/execute.pl line 174.
15:01:58  STF 14:01:58.040 - **FAILED** execute script failed. Expected return value=0 Actual=1
```

**Comment by lumpfish** [comment]
Fixed by https://github.com/AdoptOpenJDK/openjdk-systemtest/pull/369
