### ISSUE TITLE
MauveSingleThreadLoadTest fails on various platforms 

### ISSUE THREAD

**Issue by Mesbah-Alam** [AdoptOpenJDK/openjdk-systemtest#75]
**MauveSingleThreadLoadTest fails on openjdk8_j9_systemtest_x86-64_linux:** 
https://ci.adoptopenjdk.net/view/System%20tests/job/openjdk8_j9_systemtest_x86-64_linux/18/artifact/openjdk-tests/TestConfig/test_output_15187920382753/TestTargetResult.tap/*view*/
```
LT  >>> Captured test output >>>
        LT  PASS: gnu.testlet.java.math.BigInteger.multiply (number 0)
        LT  PASS: gnu.testlet.java.math.BigInteger.multiply (number 1)
        LT  PASS: gnu.testlet.java.math.BigInteger.multiply (number 2)
        LT  PASS: gnu.testlet.java.math.BigInteger.multiply (number 3)
        LT  PASS: gnu.testlet.java.math.BigInteger.multiply (number 4)
        LT  PASS: gnu.testlet.java.math.BigInteger.multiply (number 5)
        LT  PASS: gnu.testlet.java.math.BigInteger.multiply (number 6)
        LT  PASS: gnu.testlet.java.math.BigInteger.multiply (number 7)
        LT  FAIL: gnu.testlet.java.math.BigInteger.multiply (number 8)
        LT  <<<
```

 **Failure on openjdk9 hotspot Macos vm:** 
https://ci.adoptopenjdk.net/view/System%20tests/job/openjdk9_hs_systemtest_x86-64_macos/lastSuccessfulBuild/artifact/openjdk-tests/TestConfig/test_output_15196529222063/TestTargetResult.tap/*view*/

```
 LT  06:08:27.780 - First failure detected by thread: load-0. Not creating dumps as not running on an IBM JVM
        LT  06:08:27.809 - Test failed
        LT    Failure num.  = 1
        LT    Test number   = 43
        LT    Test details  = 'Mauve[gnu.testlet.java.awt.color.ColorSpace.getInstance]'
        LT    Suite number  = 0
        LT    Thread number = 0
        LT  >>> Captured test output >>>
        LT  Test failed:
        LT  java.lang.ClassNotFoundException: gnu.testlet.java.awt.color.ColorSpace.getInstance
        LT  	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
        LT  	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:185)
        LT  	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
        LT  	at java.base/java.lang.Class.forName0(Native Method)
        LT  	at java.base/java.lang.Class.forName(Class.java:292)
        LT  	at net.adoptopenjdk.loadTest.adaptors.MauveAdaptor.executeTest(MauveAdaptor.java:50)
        LT  	at net.adoptopenjdk.loadTest.LoadTestRunner$2.run(LoadTestRunner.java:177)
        LT  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        LT  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        LT  	at java.base/java.lang.Thread.run(Thread.java:844)
        LT  <<<
        LT  
```

Fails with Openjdk8 hotspot macos vm: 
https://ci.adoptopenjdk.net/view/System%20tests/job/openjdk8_hs_systemtest_x86-64_macos/lastSuccessfulBuild/artifact/openjdk-tests/TestConfig/test_output_15194062996965/TestTargetResult.tap/*view*/

Fails on openjdk9 hotspot aarch64 linux: https://ci.adoptopenjdk.net/view/System%20tests/job/openjdk9_hs_systemtest_aarch64_linux/24/console

**Comment by Mesbah-Alam** [comment]
Personal build running MauveSingleThreadLoad test on openjdk8-j9 : https://ci.adoptopenjdk.net/view/work%20in%20progress/job/test_personal/275/console

**Comment by Mesbah-Alam** [comment]
Personal build running MauveSingleThreadLoad test on openjdk8-hs: https://ci.adoptopenjdk.net/view/work%20in%20progress/job/test_personal/276/console

**Comment by Mesbah-Alam** [comment]
Both personal builds above pass. The issue seems to be an intermittent one!

**Comment by Mesbah-Alam** [comment]
This test fails on openjdk11 openj9 build, but with a new failure: 
```
LT  FAIL: gnu.testlet.javax.swing.DefaultListSelectionModel.setSelectionInterval: SINGLE_SELECTION_X (number 7)
LT  got 2 but expected 4
```

https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/362/tapResults/

I am closing this old issue at this moment. A new issue will be opened with the latest failure above.
