### ISSUE TITLE
MauveSingleInvocationLoadTest fails on various platforms

### ISSUE THREAD

**Issue by Mesbah-Alam** [AdoptOpenJDK/openjdk-systemtest#78]
**openjdk10_hs_systemtest_x86-64_linux**
https://ci.adoptopenjdk.net/view/System%20tests/job/openjdk10_hs_systemtest_x86-64_linux/
```
        LT  FAIL: gnu.testlet.javax.swing.DefaultListSelectionModel.setSelectionInterval: SINGLE_SELECTION_X (number 7)
        LT  got 2 but expected 4
```

**openjdk9_hs_systemtest_x86-64_macos:** &&  **openjdk8_hs_systemtest_x86-64_macos**
 https://ci.adoptopenjdk.net/view/System%20tests/job/openjdk9_hs_systemtest_x86-64_macos/lastSuccessfulBuild/artifact/openjdk-tests/TestConfig/test_output_15196529222063/TestTargetResult.tap/*view*/

&& 

https://ci.adoptopenjdk.net/view/System%20tests/job/openjdk8_hs_systemtest_x86-64_macos/

```
 LT  java.lang.ClassNotFoundException: gnu.testlet.java.awt.color.ColorSpace.getInstance
        LT  	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
        LT  	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:185)
        LT  	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
        LT  	at java.base/java.lang.Class.forName0(Native Method)
        LT  	at java.base/java.lang.Class.forName(Class.java:292)
        LT  	at net.adoptopenjdk.loadTest.adaptors.MauveAdaptor.executeTest(MauveAdaptor.java:50)
        LT  	at net.adoptopenjdk.loadTest.LoadTestRunner$2.run(LoadTestRunner.java:177)
        LT  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        LT  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        LT  	at java.base/java.lang.Thread.run(Thread.java:844)
```

**openjdk9_j9_systemtest_x86-64_linux**
https://ci.adoptopenjdk.net/view/System%20tests/job/openjdk9_j9_systemtest_x86-64_linux/21/console

**Comment by Mesbah-Alam** [comment]
Closing this outdated general issue. Will open more specific issues based on failures seen on sdks we support at the moment -- which are 8, 11, and 12.
