### ISSUE TITLE
OpenJDK issue: ConcurrentLoadTest fails with OpenJDK 10

### ISSUE THREAD

**Issue by Mesbah-Alam** [AdoptOpenJDK/openjdk-systemtest#87]
**Overview:**
ConcurrentLoadTest fails consistently, with OpenJDK 10, across all platforms. 

**Error:** 

```
  LT  testStarted : testAPI(net.adoptopenjdk.test.concurrent.ConcurrentSkipListMapTest)
        LT  testFinished: testAPI(net.adoptopenjdk.test.concurrent.ConcurrentSkipListMapTest)
        LT  testStarted : testStress(net.adoptopenjdk.test.concurrent.ConcurrentSkipListMapTest)
        LT  testFailure: testStress(net.adoptopenjdk.test.concurrent.ConcurrentSkipListMapTest): null
        LT  java.util.NoSuchElementException
        LT  	at java.base/java.util.concurrent.ConcurrentSkipListMap$KeyIterator.next(ConcurrentSkipListMap.java:2135)
        LT  	at net.adoptopenjdk.test.concurrent.ConcurrentSkipListMapTest.testStress(ConcurrentSkipListMapTest.java:343)
        LT  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        LT  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        LT  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        LT  	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        LT  	at junit.framework.TestCase.runTest(TestCase.java:176)
        LT  	at junit.framework.TestCase.runBare(TestCase.java:141)
        LT  	at junit.framework.TestResult$1.protect(TestResult.java:122)
        LT  	at junit.framework.TestResult.runProtected(TestResult.java:142)
        LT  	at junit.framework.TestResult.run(TestResult.java:125)
        LT  	at junit.framework.TestCase.run(TestCase.java:129)
        LT  	at junit.framework.TestSuite.runTest(TestSuite.java:252)
        LT  	at junit.framework.TestSuite.run(TestSuite.java:247)
        LT  	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)
        LT  	at org.junit.runners.Suite.runChild(Suite.java:128)
        LT  	at org.junit.runners.Suite.runChild(Suite.java:27)
        LT  	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        LT  	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        LT  	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        LT  	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        LT  	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        LT  	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        LT  	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
        LT  	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
        LT  	at net.adoptopenjdk.loadTest.adaptors.JUnitAdaptor.executeTest(JUnitAdaptor.java:129)
        LT  	at net.adoptopenjdk.loadTest.LoadTestRunner$2.run(LoadTestRunner.java:177)
        LT  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
        LT  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        LT  	at java.base/java.lang.Thread.run(Thread.java:844)
        LT  testFinished: testStress(net.adoptopenjdk.test.concurrent.ConcurrentSkipListMapTest)
```

**Example Job link:** 
https://ci.adoptopenjdk.net/view/System%20tests/job/openjdk10_hs_systemtest_aarch64_linux/10/artifact/openjdk-tests/TestConfig/test_output_15211258652983/TestTargetResult.tap/*view*/

**Note**
This is not a test issue. The actual defects will be opened in OpenJDK community. This openjdk-systemtest issue is to be used only to track the test exclusion.

**Comment by Mesbah-Alam** [comment]
PR for exclusion of this test: https://github.com/AdoptOpenJDK/openjdk-tests/pull/326

**Comment by ben-walsh** [comment]
I will pick this one up.
Given OpenJDK10 is now out of support, I will investigate what currently happens with this test against the latest nightly builds of OpenJDK11+OpenJ9, OpenJDK11+Hotspot, OpenJDK12+OpenJ9 and OpenJDK12+Hotspot.

**Comment by ben-walsh** [comment]
1x run - IN PROGRESS - https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1375
1x run - IN PROGRESS - https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1376
1x run - IN PROGRESS - https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1377
1x run - IN PROGRESS - https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1378

**Comment by ben-walsh** [comment]
10x run - IN PROGRESS - https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1379

**Comment by ben-walsh** [comment]
Confirmed failed on both OJ9 and HS on JDK11 and JDK12.

**Comment by ben-walsh** [comment]
Confirmed passed on HS on JDK8 and JDK9.
Confirmed failed on HS on JDK10.

**Comment by adamfarley** [comment]
@Mesbah-Alam - A fix for this has been introduced to jdk head, and will be backported into 12 and 11.

https://bugs.openjdk.java.net/browse/JDK-8222930

**Comment by adamfarley** [comment]
May take a little while for the fix to filter through into builds.

**Comment by Mesbah-Alam** [comment]
Thanks for the update - @adamfarley

**Comment by lumpfish** [comment]
ConcurrentLoadTest is now passing on jdk11 and jdk15.
Submitted https://github.com/AdoptOpenJDK/openjdk-systemtest/issues/87 to reinstate the tests.

**Comment by lumpfish** [comment]
Fixed by https://github.com/AdoptOpenJDK/openjdk-tests/pull/2009
