### ISSUE TITLE
Network issues on Linux/s390x machine build-marist-s390x-sles-12

### ISSUE THREAD

**Issue by sxa555** [AdoptOpenJDK/openjdk-systemtest#9]
Various tests are failing on this machine. Haven't looked into it in detail yet but I suspect there's a defective /etc/hosts entry pointing the hostname to the wrong IP based on these exceptions

```
DBLT EchoServer Using channel group - sun.nio.ch.EPollPort@ac6dd7f
DBLT Completed Asynchronous Echo Server startup - available at /148.100.110.56:38637
DBLT testStarted : testMultipleSequentialConnect(net.adoptopenjdk.test.nio2.asyncio.client.MultipleConnectAsyncTest)
DBLT MultipleConnectAsyncTest.testMultipleSequentialConnect() creating 9 connections
DBLT testFailure: testMultipleSequentialConnect(net.adoptopenjdk.test.nio2.asyncio.client.MultipleConnectAsyncTest): [Failed Assertion Exceptions:
DBLT net.adoptopenjdk.test.nio2.util.AssertionFailedException: java.net.NoRouteToHostException: No route to host
DBLT    at net.adoptopenjdk.test.nio2.asyncio.client.MultipleConnectAsyncTest$1.failed(MultipleConnectAsyncTest.java:124)
DBLT    at net.adoptopenjdk.test.nio2.asyncio.client.MultipleConnectAsyncTest$1.failed(MultipleConnectAsyncTest.java:84)
DBLT    at java.base/sun.nio.ch.Invoker.invokeUnchecked(Invoker.java:129)
DBLT    at java.base/sun.nio.ch.Invoker$2.run(Invoker.java:219)
DBLT    at java.base/sun.nio.ch.AsynchronousChannelGroupImpl$1.run(AsynchronousChannelGroupImpl.java:112)
DBLT    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
DBLT    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
DBLT    at java.base/java.lang.Thread.run(Thread.java:844)
DBLT    at java.base/jdk.internal.misc.InnocuousThread.run(InnocuousThread.java:122)
DBLT Caused by: java.net.NoRouteToHostException: No route to host
DBLT    at java.base/sun.nio.ch.UnixAsynchronousSocketChannelImpl.checkConnect(Native Method)
DBLT    at java.base/sun.nio.ch.UnixAsynchronousSocketChannelImpl.finishConnect(UnixAsynchronousSocketChannelImpl.java:251)
DBLT    at java.base/sun.nio.ch.UnixAsynchronousSocketChannelImpl.finish(UnixAsynchronousSocketChannelImpl.java:197)
DBLT    at java.base/sun.nio.ch.UnixAsynchronousSocketChannelImpl.onEvent(UnixAsynchronousSocketChannelImpl.java:212)
DBLT    at java.base/sun.nio.ch.EPollPort$EventHandlerTask.run(EPollPort.java:293)
DBLT    ... 2 more
DBLT ---
```

```
LT  13:00:23.483 - Test failed
LT    Failure num.  = 1
LT    Test number   = 3562
LT    Test details  = 'Mauve[gnu.testlet.java.net.DatagramPacket.DatagramPacketTest2]'
LT    Suite number  = 0
LT    Thread number = 0
LT  >>> Captured test output >>>
LT  Test failed:
LT  java.net.UnknownHostException: openjdk-sles12: openjdk-sles12: Name or service not known
LT      at java.base/java.net.InetAddress.getLocalHost(InetAddress.java:1631)
LT      at gnu.testlet.java.net.DatagramPacket.DatagramPacketTest2.<init>(DatagramPacketTest2.java:70)
LT      at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
LT      at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
LT      at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
LT      at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)
LT      at java.base/java.lang.Class.newInstance(Class.java:558)
LT      at net.adoptopenjdk.loadTest.adaptors.MauveAdaptor.executeTest(MauveAdaptor.java:51)
LT      at net.adoptopenjdk.loadTest.LoadTestRunner$2.run(LoadTestRunner.java:177)
LT      at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
LT      at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
LT      at java.base/java.lang.Thread.run(Thread.java:844)
LT  Caused by: java.net.UnknownHostException: openjdk-sles12: Name or service not known
LT      at java.base/java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
LT      at java.base/java.net.InetAddress$PlatformNameService.lookupAllHostAddr(InetAddress.java:924)
LT      at java.base/java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1504)
LT      at java.base/java.net.InetAddress$NameServiceAddresses.get(InetAddress.java:843)  
LT      at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1494)
LT      at java.base/java.net.InetAddress.getLocalHost(InetAddress.java:1626)
LT      ... 11 more
LT  <<<
```

**Comment by Mesbah-Alam** [comment]
@sxa555 - could you please close this issue if not required any more?

**Comment by sxa555** [comment]
@Mesbah-Alam I'm not sure as I'm no longer running the testing on a regular basis - does the test now pass on that platform? I know we've had reports of networking problems on the Linux/s390x machines recently

**Comment by Mesbah-Alam** [comment]
System tests have been running fine on Linux s390x : https://ci.adoptopenjdk.net/view/Test_system/job/openjdk11_hs_systemtest_s390x_linux/ 

The only test machine we have for Linux/s390x is `test-marist-ubuntu1604-s390x-1` : https://ci.adoptopenjdk.net/label/ci.role.test&&hw.arch.s390x&&sw.os.linux/

We do not use ` build-marist-s390x-sles-12`. So, I think this issue can be closed.
